version: 0.0.4.{build}

branches:
    only:
        - master

skip_tags: true

image:
    - Visual Studio 2017

matrix:
    fast_finish: true

build_script:
    - cmd: |
          cd src
          echo %APPVEYOR_BUILD_VERSION% > .version
          .\build.ps1 --target Pack --configuration Release

artifacts:
    - path: artifacts/**
